# Installation didn't work osx-arm64
name: chemical_CPA
channels:
  - conda-forge
dependencies:
  - python=3.8 # python=3.7 threw error with module 'typing' 
  - adjusttext
  - matplotlib
  - numpy
  - pandas
  - scanpy # scanpy=1.9.8, because scanpy=1.10.1 didn't work
  - scipy 
  - seaborn
  - scikit-learn
  - submitit
  - jupyter
  - jupytext
  - pytorch::pytorch # Works on cluster: 1.12.1 Doesn't work: 1.13.1 
  - torchmetrics
  - h5py<3.2
  - cudatoolkit=11.3
  - dglteam::dgl-cuda11.3
  - deepchem
  - rdkit=2021.09.2
  - pytest
  - pyarrow
  - pre-commit
  - seml
  - py-spy
  # UMAP
  - umap-learn
  - datashader
  - bokeh
  - holoviews
  - colorcet
  - scikit-image
  - pip
  - pip:
      - tensorflow
      - dgllife
      - scgen
